### ISSUE TITLE
BACK: Home -  Local do evento - Retornando permissão insuficiente ao realizar alteração e salvar

### ISSUE THREAD

**Issue by alvaroxsouza** [luizcdc/portalwepgcomp#240]

**Comment by luizcdc** [comment]
Álvaro, com que conta isso aconteceu? Professor admin, professor superadmin, ou professor default?

Atributos do evento teoricamente só podem ser alterados por superadmin. Se for isso, pode fechar o issue por favor

**Comment by alvaroxsouza** [comment]
Isso mesmo, foram com superadmin.
