### ISSUE TITLE
BACK (Cloud): Pipeline de deploy quebrada após PR que mexeu nas migrations

### ISSUE THREAD

**Issue by luizcdc** [luizcdc/portalwepgcomp#254]
Subi um PR que mexeu nas migrations (o prisma não estava conseguindo replicar o banco, acredito que as migrations antigas estavam corrompidas e precisavam ser descartadas).

É necessário resetar o banco e rodar o seed.ts (e talvez mais alguma coisa?) para a pipeline de deploy funcionar novamente.

Idealmente, fazer isso depois de dar merge no [PR 253](https://github.com/luizcdc/portalwepgcomp/pull/253).

@Rezende123 @Kieroth29

**Comment by ernestosrf** [comment]
Atualizei o banco de desenvolvimento com um reset, rodei o seed e dei um redeploy na pipeline. Tudo certo agora.
![image](https://github.com/user-attachments/assets/11f70237-d7b3-4915-ab75-4ffc64332150)
